version: '3.8'

services:
  # 1. VERİTABANI (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: gazete_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gazete
    ports:
      - "5432:5432" # DBeaver gibi araçlarla bağlanmak için
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Veriler silinmesin diye klasöre kaydet

  # 2. BACKEND (Go - Fiber)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gazete_backend
    restart: always
    ports:
      - "8080:8080" # API adresi: http://localhost:8080
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: gazete
      DB_PORT: 5432
    volumes:
      - ./backend:/app # Kod değişikliğini anında algılamak için
      - ./uploads:/app/uploads # Fotoğraflar burada tutulacak
    depends_on:
      - db

  # 3. FRONTEND (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gazete_frontend
    restart: always
    ports:
      - "3000:3000" # Site adresi: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Next.js'in Backend'e Docker ağı üzerinden ulaşması için
      NEXT_PUBLIC_API_URL: http://localhost:8080 
    depends_on:
      - backend